/**
 * Generate a bundled public-suffix snapshot from the raw PSL data file.
 *
 * Reads the raw list (public_suffix_list.dat) from the file path passed as the
 * first CLI argument (or stdin if none given) and writes a TypeScript module
 * containing a sorted array of public suffixes to stdout.
 *
 * Run: node scripts/generate-psl.mjs public_suffix_list.dat > src/public-suffix-data.ts
 *
 * The PSL file format:
 *   - Top-of-file comments (header).
 *   - "===BEGIN ICANN DOMAINS===" (often itself commented out, but stripped here).
 *   - One suffix per line, with sections separated by blank lines.
 *   - Wildcard lines (`*.foo.bar`) and exception lines (`!foo.bar`) — skipped.
 *   - The private section follows ICANN; we bundle BOTH sections (ICANN + private).
 */

import { readFileSync } from "node:fs";

const inputPath = process.argv[2];
const raw = inputPath ? readFileSync(inputPath, "utf8") : readFileSync(0, "utf8");
const lines = raw.split("\n");

const suffixes = new Set();

// The PSL file has two sections — ICANN (official TLDs) and PRIVATE (organisations
// that operate their own internal TLD-like suffixes, e.g. `github.io`, `cloudfront.net`).
// BOTH sections are public suffixes for our purposes; we bundle them all.
let inSuffixSection = false;

function stripComment(s) {
    // A PSL line is "commented" when it starts with '//'. Strip that prefix
    // (with optional trailing space) to recover the payload.
    return s.replace(/^\/\/?\s?/, "");
}

for (let rawLine of lines) {
    // Strip any trailing CR.
    rawLine = rawLine.replace(/\r$/, "");
    const stripped = stripComment(rawLine.trim());

    if (stripped === "===BEGIN ICANN DOMAINS===" ||
        stripped === "===BEGIN PRIVATE DOMAINS===") {
        inSuffixSection = true;
        continue;
    }
    if (stripped === "===END ICANN DOMAINS===" ||
        stripped === "===END PRIVATE DOMAINS===") {
        inSuffixSection = false;
        continue;
    }
    // If we haven't yet entered a suffix section and this is a non-comment,
    // non-blank line, treat it as part of the ICANN section (some PSL snapshots
    // omit the markers entirely).
    if (!inSuffixSection && stripped !== "" && !rawLine.startsWith("//")) {
        inSuffixSection = true;
    }

    if (!inSuffixSection) {
        continue;
    }

    // Skip comments and blank lines.
    if (rawLine.startsWith("//") || rawLine.trim() === "") {
        continue;
    }

    // Wildcard rule `*.foo.bar` — skip; the parent suffix is listed elsewhere.
    if (rawLine.startsWith("*.")) {
        continue;
    }

    // Exception rule `!foo.bar` — skip.
    if (rawLine.startsWith("!")) {
        continue;
    }

    // Bare suffix. Normalize to lowercase.
    const suffix = rawLine.trim().toLowerCase();
    if (suffix !== "") {
        suffixes.add(suffix);
    }
}

const sorted = Array.from(suffixes).sort();

const timestamp = new Date().toISOString();
const banner = `// AUTO-GENERATED by scripts/generate-psl.mjs — do not edit by hand.
// Source: public_suffix_list.dat (publicsuffix.org)
// Generated: ${timestamp}
// ICANN + private-domains sections, ${sorted.length} entries, sorted ascending.
//
// Regenerate: node scripts/generate-psl.mjs public_suffix_list.dat > src/public-suffix-data.ts
`;

const body = sorted.map((s) => `    ${JSON.stringify(s)},`).join("\n");

process.stdout.write(`${banner}
export const PUBLIC_SUFFIXES: readonly string[] = [
${body}
];
`);
